---
- name: Remediate AAA controls
  import_playbook: remediate_aaa.yml

- name: Remediate NTP controls
  import_playbook: remediate_ntp.yml

- name: Remediate SNMP controls
  import_playbook: remediate_snmp.yml

- name: Remediate SYSLOG controls
  import_playbook: remediate_syslog.yml

- name: Remediate SSH controls
  import_playbook: remediate_ssh.yml

- name: Remediate HTTP controls
  import_playbook: remediate_http.yml
