apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: netbox-worker
  namespace: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox-worker
  template:
    metadata:
      labels:
        app: netbox-worker
    spec:
      containers:
      - env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_V4
              name: netbox-secrets
        - name: API_TOKEN_PEPPER_1
          valueFrom:
            secretKeyRef:
              key: API_TOKEN_PEPPER_1
              name: netbox-secrets
        - name: DB_NAME
          value: netbox4
        - name: DB_USER
          value: netbox
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: netbox-secrets
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: '5432'
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_DB
          value: '0'
        - name: ALLOWED_HOSTS
          value: '*'
        - name: CSRF_TRUSTED_ORIGINS
          value: http://*
        - name: SKIP_SUPERUSER
          value: 'true'
        - name: AWX_URL
          value: http://192.168.1.95:30765
        - name: AWX_REMEDIATION_JT
          value: '11'
        - name: AWX_TOKEN
          valueFrom:
            secretKeyRef:
              key: AWX_TOKEN
              name: netbox-secrets
        image: netboxcommunity/netbox:v4.6.8
        imagePullPolicy: IfNotPresent
        name: netbox-worker
        command:
        - /opt/netbox/docker-entrypoint.sh
        args:
        - /opt/netbox/venv/bin/python
        - /opt/netbox/netbox/manage.py
        - rqworker
        - high
        - default
        - low
        volumeMounts:
        - name: netbox-scripts
          mountPath: /opt/netbox/netbox/scripts/remediation.py
          subPath: remediation.py
          readOnly: true
      volumes:
      - name: netbox-scripts
        configMap:
          name: netbox-scripts
