apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: netbox-postgres-data
  namespace: netbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
