apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: netbox
  namespace: netbox
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 8080
  selector:
    app: netbox
  type: NodePort
